import = [
    "~/.config/alacritty/themes/themes/nightfly.toml"
]

[font]
size = 14.0

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
]
